idf_component_register(SRCS
    "app_keyboard.cpp"
    "BleKeyboard.cpp"
    "eye_term.cpp"
    "common_esp32.cpp"
    "main_loop.cpp"
    "secrets.cpp"
    "ssh.cpp"
    "keyer.cpp"
    "keyboard.cpp"
    "tcl.cpp"
    "shadow_editor.cpp"
    "typist.cpp"
    "../lib/jimtcl/src/jim.c"
    "../lib/jimtcl/src/jimregexp.c"
    "../lib/jimtcl/src/jimiocompat.c"
    "../lib/jimtcl/src/jim-subcmd.c"
    "../lib/jimtcl/src/jim-format.c"
    "../lib/jimtcl/src/jim-array.c"
    "../lib/jimtcl/src/jim-clock.c"
    "../lib/jimtcl/src/jim-pack.c"
    "../lib/jimtcl/src/jim-nosignal.c"
    "../lib/jimtcl/src/utf8.c"
    INCLUDE_DIRS "../lib/jimtcl/src"
)
